[package]
name = "vrainc"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["cyl"]
description = "An attempt at vertical Chinese typesetting"
repository = "https://github.com/cuisir7236/vrainc"
keywords = ["An attempt at vertical Chinese typesetting"]
compiler = "0.1.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool]
