[package]
name = "vrain"
version = "0.1.0"
entrypoint = "vrain.typ"
authors = ["cyl"]
description = "wolf.typ"
keywords = ["book"]
compiler = "0.1.0"

[template]
path = "."
entrypoint = "./main.typ"

[tool]
